/**
 * ESLint flat config — React & TypeScript coding standards
 */

import js from "@eslint/js";
import globals from "globals";
import tseslint from "typescript-eslint";
import react from "eslint-plugin-react";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import testingLibrary from "eslint-plugin-testing-library";
import sonarjs from "eslint-plugin-sonarjs";
import unicorn from "eslint-plugin-unicorn";
import { globalIgnores } from "eslint/config";
import todoTicketRef from "./eslint-rules/todo-ticket-ref.js";
import maxParamsProject from "./eslint-rules/max-params-project.js";
import noExplicitUndefinedOptional from "./eslint-rules/no-explicit-undefined-optional.js";
import requireNumericEnumInitializer from "./eslint-rules/require-numeric-enum-initializer.js";
import noUnguardedJsonParse from "./eslint-rules/no-unguarded-json-parse.js";
import preferSomeOverFindCheck from "./eslint-rules/prefer-some-over-find-check.js";
import preferPositiveCondition from "./eslint-rules/prefer-positive-condition.js";
import preferIncludesOverOrChain from "./eslint-rules/prefer-includes-over-or-chain.js";
import preferJsxShortCircuit from "./eslint-rules/prefer-jsx-short-circuit.js";
import noNestedTry from "./eslint-rules/no-nested-try.js";
import noExportedMutableState from "./eslint-rules/no-exported-mutable-state.js";
import noInlineObjectParamType from "./eslint-rules/no-inline-object-param-type.js";
import preferNullishHelpers from "./eslint-rules/prefer-nullish-helpers.js";
import requireFallbackOnDeepChain from "./eslint-rules/require-fallback-on-deep-chain.js";
import noInlineRenderFunction from "./eslint-rules/no-inline-render-function.js";
import noJsxInVariable from "./eslint-rules/no-jsx-in-variable.js";
import noInlineArrayChainInJsx from "./eslint-rules/no-inline-array-chain-in-jsx.js";
import noHookReturningJsx from "./eslint-rules/no-hook-returning-jsx.js";
import noRenderFnInUsecallback from "./eslint-rules/no-render-fn-in-usecallback.js";
import noTrivialUsememo from "./eslint-rules/no-trivial-usememo.js";
import noNonHookUsePrefix from "./eslint-rules/no-non-hook-use-prefix.js";
import noInlineCurriedHandler from "./eslint-rules/no-inline-curried-handler.js";
import noInlineGuardChainHandler from "./eslint-rules/no-inline-guard-chain-handler.js";
import preferReactnodeOverJsxelementUnion from "./eslint-rules/prefer-reactnode-over-jsxelement-union.js";
import preferPropsWithChildren from "./eslint-rules/prefer-props-with-children.js";
import hoistStaticComponentConstants from "./eslint-rules/hoist-static-component-constants.js";
import requireEffectCleanup from "./eslint-rules/require-effect-cleanup.js";
import preferStateUpdaterForm from "./eslint-rules/prefer-state-updater-form.js";
import requireUsestateUserefGeneric from "./eslint-rules/require-usestate-useref-generic.js";
import preferElementRefType from "./eslint-rules/prefer-element-ref-type.js";
import preferRoleQueryOverTestid from "./eslint-rules/prefer-role-query-over-testid.js";
import noTestsInDunderFolder from "./eslint-rules/no-tests-in-dunder-folder.js";
import filenameConventionByExportShape from "./eslint-rules/filename-convention-by-export-shape.js";

const testFiles = ["**/__tests__/**", "**/*.test.{ts,tsx}", "**/*.spec.{ts,tsx}"];

export default tseslint.config(
  globalIgnores([
    "dist",
    "src/components/ui/**", // generated / UI library (e.g. shadcn)
    "src/api/generated/**", // generated API client
    "src/providers/query-keys.ts", // generated constants
    "src/constants.ts", // generated by scripts/generate-version.ts
    "e2e/**",
  ]),
  js.configs.recommended,
  ...tseslint.configs.recommended,
  // Node: CommonJS (.cjs, typical commitlint) — override typescript-eslint base (module + no-require-imports)
  {
    files: ["**/*.cjs"],
    languageOptions: {
      sourceType: "commonjs",
      globals: { ...globals.node, console: "readonly", process: "readonly", module: "readonly" },
    },
    rules: {
      "@typescript-eslint/no-require-imports": "off",
    },
  },
  // Node: repo scripts (globals only — e.g. scripts/*.mjs stays ESM)
  {
    files: ["scripts/**"],
    languageOptions: { globals: { ...globals.node, console: "readonly", process: "readonly", module: "readonly" } },
  },
  {
    files: ["**/*.{ts,tsx}"],
    plugins: {
      react,
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
      "testing-library": testingLibrary,
      sonarjs,
      unicorn,
      project: {
        rules: {
          ...maxParamsProject.rules,
          ...noExplicitUndefinedOptional.rules,
          ...requireNumericEnumInitializer.rules,
          ...noUnguardedJsonParse.rules,
          ...preferSomeOverFindCheck.rules,
          ...preferPositiveCondition.rules,
          ...preferIncludesOverOrChain.rules,
          ...preferJsxShortCircuit.rules,
          ...noNestedTry.rules,
          ...noExportedMutableState.rules,
          ...noInlineObjectParamType.rules,
          ...preferNullishHelpers.rules,
          ...requireFallbackOnDeepChain.rules,
          ...noInlineRenderFunction.rules,
          ...noJsxInVariable.rules,
          ...noInlineArrayChainInJsx.rules,
          ...noHookReturningJsx.rules,
          ...noRenderFnInUsecallback.rules,
          ...noTrivialUsememo.rules,
          ...noNonHookUsePrefix.rules,
          ...noInlineCurriedHandler.rules,
          ...noInlineGuardChainHandler.rules,
          ...preferReactnodeOverJsxelementUnion.rules,
          ...preferPropsWithChildren.rules,
          ...hoistStaticComponentConstants.rules,
          ...requireEffectCleanup.rules,
          ...preferStateUpdaterForm.rules,
          ...requireUsestateUserefGeneric.rules,
          ...preferElementRefType.rules,
          ...preferRoleQueryOverTestid.rules,
          ...noTestsInDunderFolder.rules,
          ...filenameConventionByExportShape.rules,
        },
      },
    },
    languageOptions: {
      parserOptions: {
        ecmaVersion: 2022,
        sourceType: "module",
        ecmaFeatures: { jsx: true },
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
      globals: globals.browser,
    },
    settings: {
      // eslint-plugin-react@7.37.5's "detect" path crashes under ESLint 10 flat config
      // (TypeError: contextOrFilename.getFilename is not a function) when it hits a
      // JSXFragment node — pin explicitly to sidestep that code path.
      react: { version: "19.2.8" },
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "prefer-const": "error",
      "no-var": "error",
      "no-duplicate-imports": "error",
      "no-warning-comments": ["warn", { terms: ["fixme", "xxx", "hack"], location: "anywhere" }],
      "no-console": "error",
      eqeqeq: ["error", "always"],
      "no-nested-ternary": "error",
      "no-empty": ["error", { allowEmptyCatch: false }],
      "no-useless-catch": "error",
      "max-depth": ["error", 2],
      complexity: ["error", 15],
      "sonarjs/cognitive-complexity": ["error", 15],
      "project/max-params": ["error", 1],
      "@typescript-eslint/max-params": ["error", { max: 2 }],
      "project/no-explicit-undefined-optional": "error",
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-non-null-assertion": "error",
      "@typescript-eslint/no-inferrable-types": "error",
      "@typescript-eslint/no-unused-vars": ["error", { argsIgnorePattern: "^_" }],
      "@typescript-eslint/prefer-nullish-coalescing": "error",
      "@typescript-eslint/consistent-indexed-object-style": ["error", "record"],
      "react/no-array-index-key": "error",
      "react/jsx-fragments": ["error", "syntax"],
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      "@typescript-eslint/no-floating-promises": "error",
      "@typescript-eslint/no-misused-promises": "error",
      "@typescript-eslint/only-throw-error": "error",
      "@typescript-eslint/consistent-type-definitions": ["error", "interface"],
      "func-style": ["error", "expression"],
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "lodash",
              message:
                "Use a named import from 'lodash-es' instead (tree-shakeable), e.g. import { groupBy } from 'lodash-es'.",
            },
          ],
        },
      ],
      "no-restricted-syntax": [
        "error",
        {
          selector:
            ":matches(MemberExpression[object.type='MetaProperty'][property.name='env'], MemberExpression[object.object.type='MetaProperty'][object.property.name='env'])",
          message:
            "Don't read import.meta.env directly — add a validated getter in src/utils/environment.utils.ts and import that instead.",
        },
      ],
      "react/destructuring-assignment": ["error", "always"],
      "react/jsx-curly-brace-presence": "error",
      // Replaced by project/prefer-jsx-short-circuit: `&&` short-circuit (not
      // `cond ? jsx : null`) plus `!!` / `length > 0` so non-booleans cannot leak.
      "react/jsx-no-leaked-render": "off",
      "project/prefer-jsx-short-circuit": "error",
      "no-eval": "error",
      "no-new-func": "error",
      "react/no-danger": "error",
      "unicorn/filename-case": ["error", { case: "kebabCase" }],
      "project/require-numeric-enum-initializer": "error",
      "project/no-unguarded-json-parse": "error",
      "project/prefer-some-over-find-check": "error",
      "project/prefer-positive-condition": "error",
      "project/prefer-includes-over-or-chain": "error",
      "project/no-nested-try": "error",
      "project/no-exported-mutable-state": "error",
      "project/no-inline-object-param-type": "error",
      "project/prefer-nullish-helpers": "error",
      "project/require-fallback-on-deep-chain": "error",
      "project/no-inline-render-function": "error",
      "project/no-jsx-in-variable": "error",
      "project/no-inline-array-chain-in-jsx": "error",
      "project/no-hook-returning-jsx": "error",
      "project/no-render-fn-in-usecallback": "error",
      "project/no-trivial-usememo": "error",
      "project/no-non-hook-use-prefix": "error",
      "project/no-inline-curried-handler": "error",
      "project/no-inline-guard-chain-handler": "error",
      "project/prefer-reactnode-over-jsxelement-union": "error",
      "project/prefer-props-with-children": "error",
      "project/hoist-static-component-constants": "error",
      "project/require-effect-cleanup": "error",
      "project/prefer-state-updater-form": "error",
      "project/require-usestate-useref-generic": "error",
      "project/prefer-element-ref-type": "error",
      "project/filename-convention-by-export-shape": "error",
    },
  },
  {
    files: ["src/utils/environment.utils.ts", "src/screens/tools/components/section-env-vars.tsx"],
    rules: { "no-restricted-syntax": "off" },
  },
  {
    files: ["**/*.tsx"],
    rules: {
      "max-lines": ["error", { max: 150, skipBlankLines: true, skipComments: true }],
      "max-lines-per-function": ["error", { max: 150, skipBlankLines: true, skipComments: true }],
    },
  },
  {
    files: testFiles,
    rules: {
      "testing-library/prefer-screen-queries": "error",
      "max-lines": "off",
      "max-lines-per-function": "off",
      "project/prefer-role-query-over-testid": "error",
      "project/no-tests-in-dunder-folder": "error",
    },
  },
  {
    files: ["**/*.{ts,tsx,js,jsx,cjs}"],
    plugins: { "todo-plz": todoTicketRef },
    rules: {
      "todo-plz/ticket-ref": [
        "warn",
        {
          pattern: "([A-Z0-9]+-\\d+)",
          comment: "TODO must include a ticket reference (e.g. TODO: JIRA-1234, TODO: https://…/browse/TBDT2-173)",
        },
      ],
    },
  },
  {
    files: ["**/*.ts"],
    ignores: testFiles,
    rules: {
      "max-lines": ["error", { max: 400, skipBlankLines: true, skipComments: true }],
      "max-lines-per-function": ["error", { max: 90, skipBlankLines: true, skipComments: true }],
    },
  },
  { files: ["eslint-rules/**", ".claude/hooks/**"], rules: { "todo-plz/ticket-ref": "off" } },
  {
    files: ["**/*.{mts,cjs,js,mjs}"],
    rules: { "no-console": "error" },
  },
  {
    files: ["scripts/**"],
    rules: { "no-console": "off" },
  },
  {
    files: ["src/index.ts"],
    rules: { "project/filename-convention-by-export-shape": "off" },
  },
  {
    files: ["src/playground/playground.tsx"],
    rules: {
      "react-refresh/only-export-components": "off",
    },
  }
);
