/**
 * ESLint flat config — React & TypeScript coding standards
 */

import js from "@eslint/js";
import globals from "globals";
import tseslint from "typescript-eslint";
import react from "eslint-plugin-react";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import testingLibrary from "eslint-plugin-testing-library";
import sonarjs from "eslint-plugin-sonarjs";
import unicorn from "eslint-plugin-unicorn";
import { globalIgnores } from "eslint/config";
import codingGuide, { configs as codingGuideConfigs } from "@lichens-innovation/eslint-plugin-coding-guide";

const testFiles = ["**/__tests__/**", "**/*.test.{ts,tsx}", "**/*.spec.{ts,tsx}"];

export default tseslint.config(
  globalIgnores([
    "dist",
    "src/components/ui/**", // generated / UI library (e.g. shadcn)
    "src/api/generated/**", // generated API client
    "src/providers/query-keys.ts", // generated constants
    "src/constants.ts", // generated by scripts/generate-version.ts
    "e2e/**",
  ]),
  js.configs.recommended,
  ...tseslint.configs.recommended,
  // Node: CommonJS (.cjs, typical commitlint) — override typescript-eslint base (module + no-require-imports)
  {
    files: ["**/*.cjs"],
    languageOptions: {
      sourceType: "commonjs",
      globals: { ...globals.node, console: "readonly", process: "readonly", module: "readonly" },
    },
    rules: {
      "@typescript-eslint/no-require-imports": "off",
    },
  },
  // Node: repo scripts (globals only — e.g. scripts/*.mjs stays ESM)
  {
    files: ["scripts/**"],
    languageOptions: { globals: { ...globals.node, console: "readonly", process: "readonly", module: "readonly" } },
  },
  {
    files: ["**/*.{ts,tsx}"],
    plugins: {
      react,
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
      "testing-library": testingLibrary,
      sonarjs,
      unicorn,
      "coding-guide": codingGuide,
    },
    languageOptions: {
      parserOptions: {
        ecmaVersion: 2022,
        sourceType: "module",
        ecmaFeatures: { jsx: true },
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
      globals: globals.browser,
    },
    settings: {
      // eslint-plugin-react@7.37.5's "detect" path crashes under ESLint 10 flat config
      // (TypeError: contextOrFilename.getFilename is not a function) when it hits a
      // JSXFragment node — pin explicitly to sidestep that code path.
      react: { version: "19.2.8" },
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "prefer-const": "error",
      "no-var": "error",
      "no-duplicate-imports": "error",
      "no-warning-comments": ["warn", { terms: ["fixme", "xxx", "hack"], location: "anywhere" }],
      "no-console": "error",
      eqeqeq: ["error", "always"],
      "no-nested-ternary": "error",
      "no-empty": ["error", { allowEmptyCatch: false }],
      "no-useless-catch": "error",
      "max-depth": ["error", 2],
      complexity: ["error", 15],
      "sonarjs/cognitive-complexity": ["error", 15],
      ...codingGuideConfigs.recommended.rules,
      "@typescript-eslint/max-params": ["error", { max: 2 }],
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-non-null-assertion": "error",
      "@typescript-eslint/no-inferrable-types": "error",
      "@typescript-eslint/no-unused-vars": ["error", { argsIgnorePattern: "^_" }],
      "@typescript-eslint/prefer-nullish-coalescing": "error",
      "@typescript-eslint/consistent-indexed-object-style": ["error", "record"],
      "react/no-array-index-key": "error",
      "react/jsx-fragments": ["error", "syntax"],
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      "@typescript-eslint/no-floating-promises": "error",
      "@typescript-eslint/no-misused-promises": "error",
      "@typescript-eslint/only-throw-error": "error",
      "@typescript-eslint/consistent-type-definitions": ["error", "interface"],
      "func-style": ["error", "expression"],
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "lodash",
              message:
                "Use a named import from 'lodash-es' instead (tree-shakeable), e.g. import { groupBy } from 'lodash-es'.",
            },
          ],
        },
      ],
      "no-restricted-syntax": [
        "error",
        {
          selector:
            ":matches(MemberExpression[object.type='MetaProperty'][property.name='env'], MemberExpression[object.object.type='MetaProperty'][object.property.name='env'])",
          message:
            "Don't read import.meta.env directly — add a validated getter in src/utils/environment.utils.ts and import that instead.",
        },
      ],
      "react/destructuring-assignment": ["error", "always"],
      "react/jsx-curly-brace-presence": "error",
      // Replaced by coding-guide/prefer-jsx-short-circuit: `&&` short-circuit (not
      // `cond ? jsx : null`) plus `!!` / `length > 0` so non-booleans cannot leak.
      "react/jsx-no-leaked-render": "off",
      "no-eval": "error",
      "no-new-func": "error",
      "react/no-danger": "error",
      "unicorn/filename-case": ["error", { case: "kebabCase" }],
    },
  },
  {
    files: ["src/utils/environment.utils.ts", "src/screens/tools/components/section-env-vars.tsx"],
    rules: { "no-restricted-syntax": "off" },
  },
  {
    files: ["**/*.tsx"],
    rules: {
      "max-lines": ["error", { max: 150, skipBlankLines: true, skipComments: true }],
      "max-lines-per-function": ["error", { max: 150, skipBlankLines: true, skipComments: true }],
    },
  },
  {
    files: testFiles,
    rules: {
      "testing-library/prefer-screen-queries": "error",
      "max-lines": "off",
      "max-lines-per-function": "off",
    },
  },
  {
    files: ["**/*.ts"],
    ignores: testFiles,
    rules: {
      "max-lines": ["error", { max: 400, skipBlankLines: true, skipComments: true }],
      "max-lines-per-function": ["error", { max: 90, skipBlankLines: true, skipComments: true }],
    },
  },
  { files: [".claude/hooks/**"], rules: { "coding-guide/todo-ticket-ref": "off" } },
  {
    files: ["**/*.{mts,cjs,js,mjs}"],
    rules: { "no-console": "error" },
  },
  {
    files: ["scripts/**"],
    rules: { "no-console": "off" },
  },
  {
    files: ["src/index.ts"],
    rules: { "coding-guide/filename-convention-by-export-shape": "off" },
  },
  {
    files: ["src/playground/playground.tsx"],
    rules: {
      "react-refresh/only-export-components": "off",
    },
  }
);
