import { readFileSync, writeFileSync } from "node:fs";
import { createInterface } from "node:readline";

const packageJsonPath = "./package.json";
const constantsFilename = "./src/constants.ts";

interface PackageMetadata {
  name: string;
  description: string;
  version: string;
  author: string;
  repository: string;
  [key: string]: unknown;
}

const readPackageJson = (): PackageMetadata => {
  const content = readFileSync(packageJsonPath, { encoding: "utf8" });
  try {
    return JSON.parse(content) as PackageMetadata;
  } catch (error: unknown) {
    console.error("[generate-version] Failed to parse package.json", { error });
    throw error;
  }
};

const writePackageJson = (packageData: PackageMetadata): void => {
  writeFileSync(packageJsonPath, JSON.stringify(packageData, null, 2) + "\n", {
    encoding: "utf8",
  });
};

const promptVersion = (currentVersion: string): Promise<string> => {
  const question = `\t- Current version: ${currentVersion}\n\t- New version (press Enter to keep current): `;

  return new Promise((resolve) => {
    const rl = createInterface({ input: process.stdin, output: process.stdout });
    rl.question(question, (answer) => {
      rl.close();
      const newVersion = answer.trim();
      resolve(newVersion || currentVersion);
    });
  });
};

const generateConstantsFile = (packageMetadata: PackageMetadata): string => {
  const { name, description, version, author, repository } = packageMetadata;
  const dateIso = new Date().toISOString();
  const dateOnly = dateIso.split("T")[0];

  return `/** habit-hooks-disable non-essential-comment
 * ----------------------------------------------------------------------------------------
 * Do not edit this file, it is auto-generated by scripts/generate-version.ts
 * ----------------------------------------------------------------------------------------
 */
export const APP_VERSION_INFO = Object.freeze({
  NAME: '${name}',
  DESCRIPTION: '${description}',
  REPOSITORY: '${repository}',
  AUTHOR: '${author}',
  VERSION: '${version}',
  VERSION_DATE: '${dateOnly}',
  VERSION_DATE_ISO: '${dateIso}',
})

export const LONG_VERSION_DATE = '${version} (${dateOnly})'
`;
};

interface CreateUpdatedPackageMetadataArgs {
  packageMetadata: PackageMetadata;
  newVersion: string;
}
const createUpdatedPackageMetadata = ({
  packageMetadata,
  newVersion,
}: CreateUpdatedPackageMetadataArgs): PackageMetadata => {
  const newPackageMetadata = { ...packageMetadata, version: newVersion };
  console.info(`[generate-version] Updating package.json with version "${newVersion}"`);
  writePackageJson(newPackageMetadata);
  console.info("[generate-version] package.json updated successfully");

  return newPackageMetadata;
};

const main = async (): Promise<void> => {
  console.info("[generate-version] Version generator script");

  try {
    let packageMetadata = readPackageJson();
    const currentVersion = packageMetadata.version;

    const newVersion = await promptVersion(currentVersion);
    if (newVersion !== currentVersion) {
      packageMetadata = createUpdatedPackageMetadata({ packageMetadata, newVersion });
    } else {
      console.info("[generate-version] Version unchanged", { version: currentVersion });
    }

    const data = generateConstantsFile(packageMetadata);
    console.info(`[generate-version] Writing file "${constantsFilename}"`, { version: packageMetadata.version });
    writeFileSync(constantsFilename, data, { encoding: "utf8" });
    console.info(`[generate-version] File "${constantsFilename}" written successfully`);
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.error(`[generate-version] Error: ${message}`, { err });
    process.exit(1);
  }
};

void main();
